name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - shell: bash
        env:
          CHAVE: ${{ secrets.CHAVE }}
          USUARIO: ${{ secrets.USUARIO }}
          SERVIDOR: ${{ secrets.SERVIDOR }}
          PCHAVE: "/home/runner/work/_temp/_github_workflow/foo_key"
          DESTINO: "~/public_gemini/"
        run: |
          echo -e "$CHAVE" > $PCHAVE
          chmod 600 $PCHAVE
          ssh -o StrictHostKeyChecking=no -i $PCHAVE $USUARIO@$SERVIDOR "rm -rf $DESTINO/*"
          scp -o StrictHostKeyChecking=no -i $PCHAVE $GITHUB_WORKSPACE/rodolpho/* $USUARIO@$SERVIDOR:$DESTINO
          ssh -o StrictHostKeyChecking=no -i $PCHAVE $USUARIO@$SERVIDOR "find $DESTINO -type f -exec chmod 644 {} \;"
          ssh -o StrictHostKeyChecking=no -i $PCHAVE $USUARIO@$SERVIDOR "find $DESTINO -type d -exec chmod 755 {} \;"
          shred -uz $PCHAVE
